version: '3.7'

services:
  django:
    build: ./
    command: python manage.py runserver --insecure 0.0.0.0:8000
    volumes:
      - ./:/app/
    ports:
      - 80:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgresql_db
  
  postgresql_db:
    image: postgres:12.0-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data: